# Generated by Django 3.2.18 on 2023-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trench', '0006_alter_mfamethod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfamethod',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='code generated at'),
        ),
        migrations.AddField(
            model_name='mfamethod',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='counter'),
        ),
    ]
